/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#005d97',
        'primary-container': '#0076be',
        'on-primary': '#ffffff',
        'on-primary-container': '#f5f8ff',
        'primary-fixed': '#d0e4ff',
        'primary-fixed-dim': '#9bcbff',
        'on-primary-fixed': '#001d34',
        'secondary': '#286292',
        'on-secondary': '#ffffff',
        'secondary-container': '#94c8fe',
        'on-secondary-container': '#145483',
        'secondary-fixed': '#cfe5ff',
        'on-secondary-fixed': '#001d34',
        'tertiary': '#005d95',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#0077bc',
        'on-tertiary-container': '#f6f8ff',
        'tertiary-fixed': '#cfe5ff',
        'tertiary-fixed-dim': '#98cbff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-white': '#FFFFFF',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#404751',
        'outline': '#707882',
        'outline-variant': '#c0c7d2',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#9bcbff',
        'surface-tint': '#00629f',
        'deep-navy': '#002D4A',
        'text-primary': '#000000',
        'text-secondary': '#4B5563',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
        'section-gap': '80px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      fontFamily: {
        'display': ['Hanken Grotesk', 'sans-serif'],
        'headline': ['Hanken Grotesk', 'sans-serif'],
        'body': ['Open Sans', 'sans-serif'],
        'label': ['JetBrains Mono', 'monospace'],
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}
